# Site settings
title: Bricspot
description: Life through our eyes
baseurl: "/lens-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url:
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown
